
server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/expense
    username: gui
    password: senha123
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create
  config:
    import: classpath:application-dev.yml

# Default path: /swagger-ui/index.html
springdoc:
  swagger-ui.path: /swagger
  show-actuator: true
