
INSERT INTO USUARIO (ID, USERNAME, PASSWORD) VALUES (1, 'teste', '$2a$10$7zcZ8cbo6MgIobw1qvijOOX0DT5Byo3PKBPOiu3jeh3Al8276Ebpe');

INSERT INTO ROLE (ID, ROLE_NAME) VALUES (1, 'ROLE_ADMIN');
INSERT INTO ROLE (ID, ROLE_NAME) VALUES (2, 'ROLE_USER');

INSERT INTO USUARIO_ROLE (USER_ID, ROLE_ID) VALUES (1, 1);
