
INSERT INTO USUARIO (ID, USERNAME, PASSWORD) VALUES (1, 'teste', '$10$7sKxnh4QDjc1DmeLAHm74.qSasRZO2jKxB.X6WhgjvbQ1AUzV12tW');

INSERT INTO ROLE (ID, ROLE_NAME) VALUES (1, 'ROLE_ADMIN');
INSERT INTO ROLE (ID, ROLE_NAME) VALUES (2, 'ROLE_USER');

INSERT INTO USUARIO_ROLE (USER_ID, ROLE_ID) VALUES (1, 1);
